export const INIT_MENU = [
  {
    id: 1,
    category: "Starters",
    name: "Veg Momos",
    price: 140,
    variants: ["Regular", "Extra Spicy"],
    available: true,
    img: "🥟",
  },
  {
    id: 2,
    category: "Starters",
    name: "Paneer Tikka",
    price: 220,
    variants: ["Half", "Full"],
    available: true,
    img: "🧀",
  },
  {
    id: 3,
    category: "Starters",
    name: "Crispy Corn",
    price: 180,
    variants: [],
    available: true,
    img: "🌽",
  },
  {
    id: 4,
    category: "Mains",
    name: "Butter Naan",
    price: 50,
    variants: ["Plain", "Garlic"],
    available: true,
    img: "🫓",
  },
  {
    id: 5,
    category: "Mains",
    name: "Dal Makhani",
    price: 240,
    variants: ["Half", "Full"],
    available: true,
    img: "🥘",
  },
  {
    id: 6,
    category: "Mains",
    name: "Veg Biryani",
    price: 260,
    variants: ["Regular", "Large"],
    available: true,
    img: "🍚",
  },
  {
    id: 7,
    category: "Drinks",
    name: "Masala Chai",
    price: 60,
    variants: ["Regular", "Cutting"],
    available: true,
    img: "🍵",
  },
  {
    id: 8,
    category: "Drinks",
    name: "Fresh Lime Soda",
    price: 80,
    variants: ["Sweet", "Salted"],
    available: true,
    img: "🍋",
  },
  {
    id: 9,
    category: "Desserts",
    name: "Gulab Jamun",
    price: 90,
    variants: ["2pc", "4pc"],
    available: false,
    img: "🍮",
  },
];

export const INIT_ORDERS = [
  {
    id: "T-021",
    table: "T4",
    channel: "QR",
    items: [
      { name: "Veg Momos", qty: 2, price: 140 },
      { name: "Masala Chai", qty: 1, price: 60 },
    ],
    total: 340,
    status: "preparing",
    time: "18:42",
    customer: "Walk-in",
  },
  {
    id: "W-018",
    table: "Delivery",
    channel: "WhatsApp",
    items: [
      { name: "Veg Biryani", qty: 1, price: 260 },
      { name: "Dal Makhani", qty: 1, price: 240 },
    ],
    total: 500,
    status: "received",
    time: "18:39",
    customer: "Priya S.",
  },
  {
    id: "T-020",
    table: "T2",
    channel: "QR",
    items: [
      { name: "Paneer Tikka", qty: 1, price: 220 },
      { name: "Butter Naan", qty: 3, price: 50 },
    ],
    total: 370,
    status: "ready",
    time: "18:31",
    customer: "Walk-in",
  },
];

export const INIT_CUSTOMERS = [
  {
    id: "C001",
    name: "Priya Sharma",
    phone: "+91 98765 11111",
    email: "priya@email.com",
    points: 2480,
    tier: "Gold",
    visits: 34,
    totalSpend: 18200,
    lastVisit: "2026-04-22",
    tags: ["VIP", "Birthday:May-12"],
  },
  {
    id: "C002",
    name: "Amit Kumar",
    phone: "+91 87654 22222",
    email: "amit@email.com",
    points: 1210,
    tier: "Silver",
    visits: 18,
    totalSpend: 9400,
    lastVisit: "2026-04-20",
    tags: ["Regular"],
  },
];

export const INIT_STAFF = [
  {
    id: "S1",
    name: "Deepak Kumar",
    role: "Manager",
    pin: "1234",
    outlets: ["Main Branch"],
    active: true,
  },
  {
    id: "S2",
    name: "Ritu Sharma",
    role: "Waiter",
    pin: "2345",
    outlets: ["Main Branch"],
    active: true,
  },
];

export const WEEKLY = [12400, 15800, 11200, 19600, 14300, 21800, 18420];
export const WLABELS = ["M", "T", "W", "T", "F", "S", "S"];
